name: Tweet at

on:
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Tweepy'i yükle
        run: pip install tweepy

      - name: Tweet scriptini çalıştır
        run: python tweet.py
            env:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
